import { LegalShell } from "../legal-shell";

export const dynamic = "force-static";

export default function Privacy() { return <LegalShell eyebrow="Privacy" title="Your journal belongs to you." intro="This policy explains what MigraLoom keeps on your device, what limited technical information our services may process, and the choices you have.">
  <h2>The short version</h2><p>Your migraine journal is designed to stay on your iPhone. We do not sell health information, use journal content for advertising, or require an account to use MigraLoom.</p>
  <h2>Information stored on your device</h2><p>Entries such as migraine timing and intensity, symptoms, possible triggers, medications and relief attempts, notes, daily check-ins, profile context, and generated summaries are stored locally on your device. We do not receive this journal content through MigraLoom’s normal operation.</p>
  <h2>Limited service information</h2><p>We use Google Firebase Analytics for a small set of product events related to the paywall and subscription flow, and Firebase Crashlytics for technical crash diagnostics. This may include an installation or app-instance identifier, app version, device model, operating-system information, timestamps, event names, and crash traces. We deliberately do not attach journal entries, symptoms, medications, triggers, notes, location, or other health content to these events.</p><p>RevenueCat helps synchronize purchases and subscription access. It may process an anonymous app-user identifier, the Firebase app-instance identifier, product identifiers, purchase history, and subscription lifecycle events. Apple processes App Store payments under Apple’s own terms and privacy policy.</p>
  <h2>What we do not do</h2><ul><li>We do not sell your personal or health information.</li><li>We do not use your journal to target advertising.</li><li>We do not operate a cloud copy of your journal.</li><li>We do not share journal content with clinicians unless you choose to export and share it yourself.</li></ul>
  <h2>Why we process limited service information</h2><p>We process limited analytics and diagnostics to operate, secure, troubleshoot, and improve MigraLoom, and purchase information to provide paid features and comply with financial or legal obligations. Depending on where you live, these purposes may rely on performance of our agreement, our legitimate interests in operating a reliable service, consent where required, or compliance with law.</p>
  <h2>Your choices and rights</h2><p>You can choose what to record and whether to export a visit summary. Deleting the app removes locally stored MigraLoom data from that device, so export anything you wish to keep first. Apple provides controls for purchases and subscriptions. Depending on your location, you may also have rights to request access, correction, deletion, restriction, objection, or portability for personal information we control, and to complain to your local data-protection authority.</p>
  <h2>Security, retention, and international processing</h2><p>Local data benefits from the security of your iPhone and its passcode. No system is risk-free, so keep your device and operating system up to date. Firebase, RevenueCat, and Apple may process limited service information in countries outside your own under their safeguards. We retain service information only as reasonably needed for the purposes above, provider retention settings, dispute resolution, security, and legal obligations.</p>
  <h2>The website</h2><p>The MigraLoom website does not require an account and does not use advertising trackers. Our hosting provider may process ordinary request information such as IP address, browser information, requested page, and timestamps to deliver and secure the site. If you email us, we process your address and message to respond; please do not include sensitive medical information.</p>
  <h2>Children and changes</h2><p>MigraLoom is not directed to children under 13. We may update this policy as the product develops and will post a revised effective date here.</p>
  <h2>Contact</h2><p>MigraLoom is responsible for the information described in this policy. Questions, rights requests, or privacy concerns can be sent to <a href="mailto:support@migraloom.com">support@migraloom.com</a>.</p>
</LegalShell>; }
