import { LegalShell } from "../legal-shell";

export default function Privacy() { return <LegalShell eyebrow="Privacy" title="Your journal belongs to you." intro="This policy explains what MigraLoom keeps on your device, what limited technical information our services may process, and the choices you have.">
  <h2>The short version</h2><p>Your migraine journal is designed to stay on your iPhone. We do not sell health information, use journal content for advertising, or require an account for the planned launch.</p>
  <h2>Information stored on your device</h2><p>Entries such as migraine timing and intensity, symptoms, possible triggers, medications and relief attempts, notes, daily check-ins, profile context, and generated summaries are stored locally on your device. We do not receive this journal content through MigraLoom’s normal operation.</p>
  <h2>Limited service information</h2><p>We use Firebase for limited product analytics and crash diagnostics. This may include app version, device or operating-system information, screen-level usage events, and technical crash details. We design these events not to include your journal entries, symptoms, medications, triggers, notes, or other health content.</p><p>RevenueCat helps manage subscription status and purchase entitlements. It may process a pseudonymous app user identifier, product and purchase information, and subscription lifecycle events. Apple processes App Store payments under Apple’s own terms and privacy policy.</p>
  <h2>What we do not do</h2><ul><li>We do not sell your personal or health information.</li><li>We do not use your journal to target advertising.</li><li>We do not operate a cloud copy of your journal for the planned launch.</li><li>We do not share journal content with clinicians unless you choose to export and share it yourself.</li></ul>
  <h2>Your choices</h2><p>You can choose what to record and whether to export a visit summary. Deleting the app removes locally stored MigraLoom data from that device, so export anything you wish to keep first. Apple provides controls for purchases and subscriptions.</p>
  <h2>Security and retention</h2><p>Local data benefits from the security of your iPhone and its passcode. No system is risk-free, so keep your device and operating system up to date. Technical analytics and subscription records are retained only as reasonably needed to operate, secure, and improve the service or meet legal obligations.</p>
  <h2>Children and changes</h2><p>MigraLoom is not directed to children under 13. We may update this policy as the product develops and will post a revised effective date here.</p>
  <h2>Contact</h2><p>Questions or privacy requests can be sent to <a href="mailto:hello@migraloom.com">hello@migraloom.com</a>.</p>
</LegalShell>; }
