const moments = [
  ["08:14", "Started", "Left temple · moderate", "coral"],
  ["10:06", "Tried relief", "Quiet room + water", "lavender"],
  ["12:32", "Eased", "A little better", "mint"],
];

export default function Home() {
  return <main>
    <nav className="nav-shell" aria-label="Main navigation"><a className="wordmark" href="#top"><span className="mark"><i/><i/><i/></span>Ivory Trace</a><a className="nav-link" href="#approach">Our approach</a><a className="nav-cta" href="#early-access">Get early access</a></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">A private migraine journal</p><h1>Make space for <em>your</em> story.</h1><p className="hero-text">A quieter way to remember the days that matter—so your next conversation with a clinician starts with clarity, not guesswork.</p><a className="primary-button" href="#early-access">Join the early list <b>→</b></a><p className="small-note">Built for iPhone · Your record stays on your device</p></div><div className="phone-wrap" aria-label="A preview of the Ivory Trace app"><div className="orbit one"/><div className="orbit two"/><div className="phone"><div className="phone-top"><span>9:41</span><span className="sensor"/></div><div className="phone-body"><p className="app-kicker">Tuesday, 16 July</p><h2>How are you<br/>right now?</h2><div className="signal-card"><div><span>Current record</span><b>03:18</b></div><div className="signal-line">{[15,29,42,31,49,38,22,12].map((h,i)=><i key={i} style={{height:h}}/>)}</div><small>Started at 08:14 <span>Moderate</span></small></div><div className="app-action"><i className="warm"/>Add what changed <b>+</b></div><div className="app-action subtle"><i className="cool"/>End this record <b>→</b></div></div><div className="home-bar"/></div></div></section>
    <section className="quiet-band" id="approach"><p className="eyebrow">Not another health dashboard</p><p>There’s no score to chase. Just a gentle record of what happened, in the language that feels right to you.</p></section>
    <section className="record-section"><div className="section-intro"><p className="eyebrow">A record, not a report card</p><h2>Small details become a clearer picture.</h2><p>Start when something begins. Add only what feels useful. Ivory Trace holds the thread together for when you need it later.</p></div><div className="timeline-card"><header><span>One day, held gently</span><span>16 Jul</span></header><div className="timeline-list">{moments.map(([time,label,note,tone])=><div className="moment" key={time}><time>{time}</time><i className={tone}/><div><strong>{label}</strong><p>{note}</p></div></div>)}</div><em>Nothing more is required.</em></div></section>
    <section className="privacy-section"><div className="privacy-number">01</div><div><p className="eyebrow">Private by design</p><h2>Your experience isn’t a product.</h2></div><p>Journal entries live on your iPhone. We don’t sell health information, and we don’t build an advertising profile around your difficult days.</p></section>
    <section className="closing" id="early-access"><p className="eyebrow">Coming soon</p><h2>A steadier place to<br/><em>remember.</em></h2><p>Ivory Trace is being shaped with care. Join the early list to be first to know when it’s ready.</p><a className="primary-button" href="mailto:hello@ivorytrace.app?subject=Ivory%20Trace%20early%20access">Request early access <b>→</b></a></section>
    <footer><span>© 2026 Ivory Trace</span><span>Made for the days worth remembering.</span></footer>
  </main>;
}
